//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTalkLib.NET.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<RSAKeyValue><Modulus>kGxMjlagPVZG2okBD1IQ/cKWnAIKt+38F2hOoZDeoizqe2Dxyc15qQsMoablWvmM+kHj94R5OskweWs5JK2GK6YvbISP31fsLgvtvlv5HB4y0IrnYDMtuDKC6q6f7TvCFswC50tJzDSvUXuV/+ffH2GVtfmfStbWCNCTkZXRIBM=</Modulus><Exponent>AQAB</Exponent><P>15Go+zOzmsEfR72rkTYgu7jaUV2Z5/XYTS17mGwJYdM7zWCO7vBBuEIaR8TYxP4DJCN2vdBKUw2D8TO717uygw==</P><Q>q4KiWupn6YzxHHf6BrPQkKWT8ICGb/oOvbMM9JQZQCJRnErmFLMM41zB92fvewnJ7jZbAVxBJDUs9b5Ym+YnMQ==</Q><DP>HItXGtw/vhAweiltXG8UaocRsZB5XrO5Do8lPIuhumhkFM/iXVVG/oUSQcqZAYy5EcH4aS35iYHSpM+64dgizQ==</DP><DQ>iI4WXnTMD3QcdSJBfBynLsPmqlJqt7VND1UEN6fDAwFQITSxREHbPRuZhDbIwhnlITk99DNT2lRMW80WF+qDwQ==</DQ><InverseQ>YaH7RrCxaHOv9KOIYWPrPal+7bVHU6xeCjFk6vt3naEhwfnFqa/CVYw5t/PR538K/h2xJnbsRT3opjw7P500iQ==</InverseQ><D>XfF0YupKVVu3vxN7UwHo94gJ+/UAD+CIKJm6/DGGACwDYroOzVwRFTqQvt4XNvQ5FdiidzD+wpR4KaLrisYtDV/El/LkIaOXqGaew81UqF/RLRWhJJ5yOYj0gaypilo8x+jmRPoCfJSCNiBTuNY+o9XSeYTje0SqTXc1inYgFkE=</D></RSAKeyValue>")]
        public string PrivateKey {
            get {
                return ((string)(this["PrivateKey"]));
            }
        }
    }
}
